use_frameworks!

target 'Blockstack_Example' do
  pod 'Blockstack', :path => '../'

  target 'Blockstack_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
