use_frameworks!

target 'Blockstack_Example' do
  pod 'Blockstack', :path => '../'
end

target 'Blockstack_Tests' do
  inherit! :search_paths

  pod 'Blockstack', :path => '../'
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
end
